server:
  port: 8818

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_mservice?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
